name: "Build Image"

on:
  pull_request:
    branches:
      - main
      - beta

  release:
    types: [published]

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
      name_suffix: ${{ steps.eventCheck.outputs.nameSuffix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Get git sha as on PR gitversion provides incorrect sha
        id: version
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "Github event is a $EVENT_NAME"
          if [ "$EVENT_NAME" = "pull_request" ]; then
              sha=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`
              echo "::set-output name=version::${{ github.event.pull_request.head.ref }}-${sha}"
          elif [ "$EVENT_NAME" = "release" ]; then
              echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}"
          else
              echo "invalid event type ${EVENT_NAME}"
              exit 1
          fi
      - name: Generate Image name dependend on github event
        id: eventCheck
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=nameSuffix::-pr"
          elif [ "$EVENT_NAME" = "release" ]; then
              echo "::set-output name=nameSuffix::"
          fi

  dumpversions:
    name: "Dump"
    runs-on: ubuntu-latest
    needs: calculate-version

    steps:
      - name: "Dump"
        run: |
          echo "image name is ${{ needs.calculate-version.outputs.version }}"
          echo "name suffix is ${{ needs.calculate-version.outputs.name_suffix }}"
