name: Release
on:
  pull_request:
  push:
    branches:
      - main
      - beta

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release
        env:
          # Must be a PAT, not GITHUB_TOKEN. Otherwise other workflows are not triggered!
          GITHUB_TOKEN: ${{ secrets.SEMVER_SECRET }}
        run: |
          wget https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
          bash install.sh
          nvm install 'lts/*' && npx semantic-release
